name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Set up Ruby
      uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: ruby
        bundler-cache: false

    - name: Install gems
      run: bundle install

    - name: Show outdated gems
      run: bundle outdated || true

    - name: Show gems to be updated with default cooldown
      run: |
        bundle update --all
        git diff
        git checkout .

    - name: Show gems to be updated with --cooldown=7
      run: |
        bundle update --all --cooldown=7
        git diff
        git checkout .
